sudo: required

services:
  - docker

language: java
dist: bionic

jdk:
  - openjdk11

cache:
  directories:
    - $HOME/.m2

branches:
  only:
    - master

env:
  - DOCKER_IMAGE=prpo51/filestorage:1.0.0-SNAPSHOT-$TRAVIS_JOB_NUMBER

script:
  - mvn clean package -U
  - docker build -t "$DOCKER_IMAGE" .
  - docker tag prpo51/filestorage:1.0.0-SNAPSHOT-$TRAVIS_JOB_NUMBER prpo51/filestorage:withoutAWSCredentials

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push "$DOCKER_IMAGE"
  - docker push prpo51/filestorage:awsCredentialsFromETCD
